// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mergePeaks
Rcpp::DataFrame mergePeaks(Rcpp::DataFrame data, int maxGap);
RcppExport SEXP DiffBind_mergePeaks(SEXP dataSEXP, SEXP maxGapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type maxGap(maxGapSEXP);
    rcpp_result_gen = Rcpp::wrap(mergePeaks(data, maxGap));
    return rcpp_result_gen;
END_RCPP
}
// mergeScores
Rcpp::List mergeScores(Rcpp::DataFrame sMerged, Rcpp::NumericVector sScore, Rcpp::DataFrame sPeaks);
RcppExport SEXP DiffBind_mergeScores(SEXP sMergedSEXP, SEXP sScoreSEXP, SEXP sPeaksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type sMerged(sMergedSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sScore(sScoreSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type sPeaks(sPeaksSEXP);
    rcpp_result_gen = Rcpp::wrap(mergeScores(sMerged, sScore, sPeaks));
    return rcpp_result_gen;
END_RCPP
}
// peakOrder
Rcpp::RObject peakOrder(SEXP schrom, SEXP sleft, SEXP sright);
RcppExport SEXP DiffBind_peakOrder(SEXP schromSEXP, SEXP sleftSEXP, SEXP srightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type schrom(schromSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sleft(sleftSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sright(srightSEXP);
    rcpp_result_gen = Rcpp::wrap(peakOrder(schrom, sleft, sright));
    return rcpp_result_gen;
END_RCPP
}
